name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "DB"
database_name = "newsnow-db"
database_id = "8f717f41-4b97-4b35-8fbc-57d42bb378a4"
